{{- if .Values.service.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: "{{.Release.Name }}-wireguard"
  labels:
    app: "{{ .Release.Name }}-wireguard"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: wg
    protocol: UDP
    port: {{ .Values.service.port }}
    targetPort: 51820
    {{- if .Values.service.type | eq "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: "{{ .Release.Name }}-wireguard"
{{- end }}